# Generated by Django 4.2.5 on 2023-09-14 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.file_path


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postmodel",
            name="likes",
        ),
        migrations.AlterField(
            model_name="postmodel",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=posts.file_path.custom_upload_path
            ),
        ),
        migrations.CreateModel(
            name="PostsLikesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_likes",
                        to="posts.postmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="like_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
