version: '3.11'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${PSQL_DB_NAME}
      POSTGRES_USER: ${PSQL_USERNAME}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
